silx-kit/h5grove

h5grove/content.py
h5grove/models.py
setup.py

Previously, `selection` had to be a string which hampers reusability if the caller of `.data` already has a valid slice (`int`, `slice` or a tuple of these).
Also add a setup.py command to lint for local dev

Allow selection to be a valid slice in data and data_stats

---

h5grove/content.py

Using [ravel](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html) instead of [flatten](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html) to spare a memory copy.

Using numpy.ravel rather than ndarray.flatten to spare a copy

---

.github/workflows/lint-test.yml
h5grove/tornadoutils.py

`path` and `attr_keys` should be recovered without processing spaces.
Otherwise, an entity with name `the_path ` (mind the trailing space) is recovered as `the_path` raising a 404: https://github.com/silx-kit/h5web/issues/887

Do not strip path and attr_keys query args in tornado

---

h5grove/encoders.py
h5grove/flaskutils.py
h5grove/tornadoutils.py

The `Content-Length` header is needed to display download progress: https://github.com/silx-kit/h5web/pull/908.
Flask already adds it automatically in the `flask.Response` object so I add it manually for tornado.
We could argue that the header could be set when creating the `h5grove.Response` but as Flask adds it already, perhaps it is easier that the implementing back-end has the responsibility of adding it?
What do you think @t20100 @axelboc ?

Add content-length header

---

h5grove/encoders.py

To solve recursion loops when looking at `float128`: https://github.com/silx-kit/jupyterlab-h5web/issues/84

Convert float128 in float when serializing to JSON

---

h5grove/encoders.py

Some distributions of numpy don't work with float128 (see https://stackoverflow.com/questions/29820829/cannot-use-128bit-float-in-python-on-64bit-architecture)
I've added a simple check to prevent errors

Fix handling of np.float128

---

docs/_static/api.yaml
h5grove/content.py
h5grove/encoders.py
h5grove/flaskutils.py
h5grove/tornadoutils.py
h5grove/utils.py
test/base_test.py

This PR adds a `dtype` query param to the `/data/` endpoint and the corresponding `dtype` argument to the `encode` function.
As it is now, it is backward compatible when `dtype` is not provided, but we might want to change that:
Only the `bin` format sanitizes the array while the other formats do not. Only considering `h5grove`, it sounds a random choice...
This "sanitize" behavior can be provided through e.g., `dtype=safe` (or 'typedarray') and by default the data is returned as is for all `format`s.
This provides a generic solution to #61.
closes #61

Added `dtype` argument to `encode` and `/data/` endpoint

---

.bumpversion.cfg
CONTRIBUTING.md

This allows to tag beta versions and to go back to releases with a single `--new-version` to explicitly pass

Add support of pre-releases to bump2version

---

example/fastapi_app.py
h5grove/fastapi_router.py
setup.cfg
test/base_test.py
test/conftest.py
test/test_fastapi.py

I found that you already have "blueprints" for flask and tornado. A project I work on uses fastapi. So I figured it will be nice to have a plug n play for fastapi too. You could still do it through the WSGI middleware. But this seems cleaner. 
I must say the implementation could be better. Especially with how the /data/ endpoint handles documentation of the two return types. This could be something you could work up from.
I'm happy with the functionality at least right now. It can easily be loaded up under a route in a bigger fastapi app.
I left out docs generation and tests. This is something I believe would be better for the maintainers to setup as they like. I hope that's okay! Feel free to edit this fork however you like :)

Added a fastapi router

---

docs/_static/api.yaml
h5grove/content.py
h5grove/models.py
h5grove/utils.py
test/base_test.py

Let's take the [example from Numpy](https://numpy.org/doc/stable/user/basics.rec.html#introduction):
```py
with h5py.File("test.h5", "w") as h5file:
h5file.create_dataset(
"dogs",
data=np.array(
[("Rex", 9, 81.0), ("Fido", 3, 27.0)],
dtype=[("name", "S10"), ("age", "i4"), ("weight", "f4")],
),
)
```
When asking for the metadata, h5grove was returning:
```
{
...
dtype='|V18'
}
```
Now it returns
```
{
...
dtype={"name": "|S10", "age": "<i4", "weight": "<f4"}
}
```

Improve dtype for compound datasets

---

h5grove/fastapi_utils.py
h5grove/flask_utils.py
h5grove/tornado_utils.py
test/base_test.py
test/conftest.py
test/test_fastapi.py
test/test_flask.py
test/test_tornado.py

In `..._utils`, we return 404 if the file/entity is not found. Then, it makes sense to return 403 if the file cannot be read.

Return 403 on PermissionError

---

docs/_static/api.yaml
h5grove/content.py
h5grove/fastapi_utils.py
h5grove/flask_utils.py
h5grove/tornado_utils.py
h5grove/utils.py
setup.cfg
test/base_test.py

For https://github.com/silx-kit/h5web/issues/1348, we need to implement an endpoint that either:
- search for a pattern in the file
- returns a list of paths so that the client can search inside
For now, I choose the latter solution with a new endpoints called `paths` that returns the list of all the HDF5 paths in the file. Query arg of the other endpoints were reused:
- `path`: gives the base upon which the paths are generated. Can be used to generate paths of a subtree. Defaults to `/` (root).
- `resolve_links`: whether links should be resolved. Default to `ONLY_VALID`.

Implement paths endpoint

---

docs/_static/api.yaml
h5grove/content.py
h5grove/encoders.py
h5grove/fastapi_utils.py
h5grove/flask_utils.py
h5grove/tornado_utils.py
h5grove/utils.py
test/base_test.py
test/conftest.py
test/test_tornado.py
test/test_utils.py

A discussion with Valentin showed me that the server was returning 500 errors when the query arguments were invalid (i.e. not expected or malformed).
As this error is a bit cryptic for end-users, I tried to improve this by adding a new kind of error `QueryArgumentError` that is used to return [422](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422) when query arguments do not match what h5grove expects (following the recommendation in https://stackoverflow.com/questions/3050518/what-http-status-response-code-should-i-use-if-the-request-is-missing-a-required).
I also had to refactor the tests to be able to test for this new error code (done in a separate commit)

Return 422 with error message on query arg errors

---

CONTRIBUTING.md
docs/_static/api.yaml
docs/conf.py
h5grove/content.py
h5grove/fastapi_utils.py
h5grove/flask_utils.py
h5grove/models.py
h5grove/tornado_utils.py
h5grove/utils.py
setup.cfg
tasks.py
test/base_test.py
test/test_benchmark_data.py
test/test_fastapi.py
test/test_flask.py
test/test_tornado.py

The new [snapshot test](https://github.com/silx-kit/h5web/blob/main/packages/app/src/providers/h5grove/__snapshots__/h5grove-api.test.ts.snap) of `H5GroveApi` in H5Web reveals that a lot of advanced HDF5 types are incorrectly parsed or simply marked as unknown.
This is due to the fact that h5grove's `/meta/` endpoint currently provides only a very basic `dtype` string (or dict of `dtype` strings for compound datasets), which is not sufficient and sometimes inaccurate (e.g. `|O` for variable-length ASCII strings instead of `|S`).
Following h5py's [low-level API](https://api.h5py.org/h5t.html) and taking inspiration from [h5wasm](https://github.com/usnistgov/h5wasm/blob/main/src/hdf5_util.cc#L245), I modify the dataset/attribute metadata response to include a `type` dictionary with all the …

Provide more metadata for HDF5 types

---

.github/workflows/lint-test.yml
.github/workflows/release.yml
CONTRIBUTING.md
setup.cfg
tasks.py

- `invoke doc` now rebuilds the documentation site with live reload;
- The old `doc` task is renamed to `build`.

Add `sphinx-autobuild` and corresponding task

---

h5grove/utils.py

Letting (u)int16 through without conversion when using `dtype-safe`. `BigInt64Array` and `BigUint64Array` are now [broadly supported](https://caniuse.com/mdn-javascript_builtins_bigint64array).
I've considered adding another `dtype` query argument value, but not sure it's worth it.

Consider (u)int64 as safe

---

h5grove/content.py
test/base_test.py

Fix #84 
Uses the low-level `visit`: https://github.com/h5py/h5py/issues/671#issuecomment-1866088248

The paths endpoint now also includes links

---

CONTRIBUTING.md
h5grove/encoders.py
tasks.py

Fetching an opaque binary dataset with `format=bin` was throwing a 422 error.

Allow `bin` format for non-numeric content

---

test/base_test.py
test/utils.py

- `format=tiff` and `format=csv` with numeric array
- `format=bin` with opaque dataset
This increases the coverage by a couple of percentage points to 94%. I also reorganise the tests a bit to avoid testing the same things twice.

Add more tests for /data/ endpoint

---

h5grove/encoders.py

1. https://h5web.panosc.eu/h5grove?file=sample.h5
2. Select `/complex256_scalar` or `/complex256_2D`
3. 500 error
h5grove fails in `encoders.py`, when serializing `complex256` values to JSON with [orjson](https://github.com/silx-kit/h5grove/blob/main/h5grove/encoders.py#L48). There's an infinite recursion call in `orjson_default`, on [line 27](https://github.com/silx-kit/h5grove/blob/main/h5grove/encoders.py#L27).
With `complex64` or `complex128` scalars, I trace two calls to `orjson_default`:
1. During the first call, the condition that matches first is `isinstance(o, (np.generic, np.ndarray))` => `o.tolist()` is called and returned.
2. This triggers a second call, during which the condition that matches first is now `isinstance(o, complex)` => `[o.real, o.imag]` is returned.
With …

Fix serialization of complex256 objects to JSON

---

h5grove/fastapi_utils.py
h5grove/flask_utils.py
h5grove/tornado_utils.py
test/base_test.py

The goal is to be compatible with tools like [`wait-on`](https://github.com/jeffbski/wait-on). See https://github.com/silx-kit/h5web/pull/1596#discussion_r1532226154

Add "/" GET/HEAD endpoints to check server status

---

h5grove/content.py
h5grove/encoders.py
setup.cfg
test/base_test.py
test/utils.py

Fix #94 
Also brings support for Numpy v2. See the discussion at https://github.com/silx-kit/h5grove/issues/94 for more info:
> As a rule of thumb, using `np.asarray` should be fine. Also, we have to remove the `copy=False` arg since it is visibly impossible to avoid copying when the argument is a scalar or a nested sequence (lists): https://numpy.org/devdocs/reference/generated/numpy.asarray.html#numpy.asarray
>
> By using `copy=None` (the default behaviour), copy is avoided when possible (ex: when the argument is a numpy array) but allowed when there is no other choice (as I said, scalars and nested sequences)

Allow copy for scalar and nested sequences when converting data to numpy arrays

---

h5grove/content.py
test/base_test.py

Addresses https://github.com/silx-kit/h5web/issues/1699

Support reading metadata of committed datatypes

---

docs/conf.py
h5grove/content.py
h5grove/encoders.py
h5grove/fastapi_utils.py
h5grove/flask_utils.py
h5grove/models.py
h5grove/tornado_utils.py
h5grove/utils.py
setup.cfg
test/base_test.py
test/conftest.py
test/test_benchmark_data.py
test/test_fastapi.py
test/test_flask.py
test/test_tornado.py
test/utils.py

Addresses https://github.com/silx-kit/h5grove/pull/96#discussion_r1735657971

Define metadata return types

---

.github/workflows/lint-test.yml
test/base_test.py

https://github.com/silx-kit/h5grove/pull/97#issuecomment-2317421925

Add CI test for Python 3.12

---

h5grove/utils.py
test/base_test.py

This follows https://github.com/silx-kit/h5web/pull/1692 and https://github.com/usnistgov/h5wasm/pull/76

Fix fetching boolean data as binary
